name: tests

on:
  push:
    paths:
      - "R/**"
      - "tests/**"
      - "DESCRIPTION"
      - "NAMESPACE"
      - ".github/workflows/check.yml"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::testthat

      - name: Run tests
        run: Rscript -e 'testthat::test_local(reporter = "summary", stop_on_failure = TRUE)'
